### ISSUE TITLE
Parsing input file

### ISSUE THREAD

**Issue by ydooWoody** [ydooWoody/LSRouting#2]
Input file has 2 parts, the connections and the packets.

The first line needs to be saved by the manager (number of routers), this effects the number of processes spawned.

The next set of values up until -1 EOF indicator are links. Should be be parsed and saved locally (maybe as an object of some sort). These will be sent to the src router, so knowing that will be important.

The final set are packets to send to routers, again in (src, dest) format. Parse and store these appropriately. -1 marks EOF.

**Comment by nikradaev** [comment]
Done
